### ISSUE TITLE
flann is very slow in matlab...

### ISSUE THREAD

**Issue by HaveF** [mariusmuja/flann#97]
I have no idea why flann is very very slow in matlab...
I just implement knn myself with pure matlab code.
And compare it with flann. 
the pure matlab code, it only need 4 seconds.
flann matlab wrap, it need 50~seconds...

I have no idea what is wrong.
Search the web but have no idea.
1. Did I install wrong?
   I build the git source with vs2010 debug/x64.
   After that, I copy nearest_neighbors.mexw64 to flann-master\src\matlab,
   and add the path to matlab path...
   Do I need add some pathes to system?
2. Did I test wrong?
   the test code is extremely easy...

``` matlab
...set dataset, testset...
tic;
parameters.algorithm = 'linear';
k=1;
%[index, parameters, speedup] = flann_build_index(dataset, build_params);
%[result, dists] = flann_search(index, testset, k, parameters);
[result, dists] = flann_search(dataset, testset, k, parameters);
ypred = ytrain(result);
errorRate = mean(ypred ~= ytest);
fprintf('Error Rate: %.2f%%\n',100*errorRate);
t = toc; fprintf('Total Time: %.2f seconds\n',t);
end
```

**Comment by aiohalaziz** [comment]
does it work by VS14 2015 64 bit?
in my system Cmake I see many error

1)
CMake Warning (dev) at CMakeLists.txt:18 (if):
  Policy CMP0054 is not set: Only interpret if() arguments as variables or
  keywords when unquoted.  Run "cmake --help-policy CMP0054" for policy
  details.  Use the cmake_policy command to set the policy and suppress this
  warning.

  Quoted variables like "MSVC" will no longer be dereferenced when the policy
  is set to NEW.  Since the policy is not set the OLD behavior will be used.
This warning is for project developers.  Use -Wno-dev to suppress it.

2)
CMake Warning (dev) at CMakeLists.txt:22 (if):
  Policy CMP0054 is not set: Only interpret if() arguments as variables or
  keywords when unquoted.  Run "cmake --help-policy CMP0054" for policy
  details.  Use the cmake_policy command to set the policy and suppress this
  warning.

  Quoted variables like "MSVC" will no longer be dereferenced when the policy
  is set to NEW.  Since the policy is not set the OLD behavior will be used.
This warning is for project developers.  Use -Wno-dev to suppress it.

3)
Could NOT find PythonInterp (missing:  PYTHON_EXECUTABLE) 
Could NOT find HDF5 (missing:  HDF5_LIBRARIES HDF5_INCLUDE_DIRS HDF5_HL_LIBRARIES) 
CMake Warning at CMakeLists.txt:76 (message):
  hdf5 library not found, some tests will not be run


Could NOT find MPI_C (missing:  MPI_C_LIBRARIES MPI_C_INCLUDE_PATH) 
Could NOT find MPI_CXX (missing:  MPI_CXX_LIBRARIES MPI_CXX_INCLUDE_PATH) 
CMake Warning at CMakeLists.txt:95 (message):
  Could not find an MPI library.  Define the MPI_COMPILER variable to the
  path of your MPI compiler.


CMake Warning at CMakeLists.txt:100 (message):
  For MPI support the Parallel HDF5 library is required.

4)
Could NOT find GTest (missing:  GTEST_LIBRARY GTEST_INCLUDE_DIR GTEST_MAIN_LIBRARY) 
CMake Warning at CMakeLists.txt:115 (message):
  gtest library not found, some tests will not be run


CUDA_TOOLKIT_ROOT_DIR not found or specified
Could NOT find CUDA (missing:  CUDA_TOOLKIT_ROOT_DIR CUDA_NVCC_EXECUTABLE CUDA_INCLUDE_DIRS CUDA_CUDART_LIBRARY) 
CUDA not found, CUDA library will not be built
Found MATLAB at: G:/Program Files/MATLAB/R2016a/bin
hdf5 library not found, not compiling flann_example.cpp
CMake Warning (dev) at test/CMakeLists.txt:4 (add_custom_target):
  Policy CMP0037 is not set: Target names should not be reserved and should
  match a validity pattern.  Run "cmake --help-policy CMP0037" for policy
  details.  Use the cmake_policy command to set the policy and suppress this
  warning.

  The target name "test" is reserved or not valid for certain CMake features,
  such as generator expressions, and may result in undefined behavior.
This warning is for project developers.  Use -Wno-dev to suppress it.

Could NOT find LATEX (missing:  LATEX_COMPILER) 
Install prefix: F:/jozve book/arshad/end/ok/sea vision/recog/surf/flann
Build type: RelWithDebInfo
Building C bindings: ON
Building python bindings: OFF
Building matlab bindings: ON
Building CUDA library: OFF
Using OpenMP support: ON
Using MPI support: OFF
Configuring done
Generating done
